import type { FieldSpot, TacticalFieldPreset } from './types';

// Coordinates are authored for a right-handed striker: off side is left of screen.
// Mirror x around 50 for a left-handed striker. The bowler is implicit; every preset
// contains the wicketkeeper plus nine other fielders (10 markers total).
const spot = (
  id: string,
  name: string,
  x: number,
  y: number,
  side: FieldSpot['side'],
  depth: FieldSpot['depth'],
  role: string,
  behindSquareLeg = false,
): FieldSpot => ({ id, name, x, y, side, depth, role, behindSquareLeg });

const keeper = spot('wk', 'Wicketkeeper', 50, 88, 'straight', 'close', 'Catch edges; take returns and stumpings');

export const TACTICAL_FIELD_PRESETS: TacticalFieldPreset[] = [
  {
    id: 'pace_outswing_attack',
    name: 'Pace — Away Swing Attack',
    intent: 'attack',
    maxOutsideCircle: 1,
    positions: [
      keeper,
      spot('slip1', '1st Slip', 43, 83, 'off', 'close', 'Primary outside-edge catcher'),
      spot('slip2', '2nd Slip', 36, 79, 'off', 'close', 'Thicker outside edges'),
      spot('gully', 'Gully', 26, 70, 'off', 'close', 'Square edge from hard hands'),
      spot('point', 'Point', 18, 56, 'off', 'inner_ring', 'Save cut and square drive'),
      spot('cover', 'Cover', 26, 40, 'off', 'inner_ring', 'Make the drive earn its run'),
      spot('midoff', 'Mid-off', 41, 29, 'off', 'inner_ring', 'Straight-drive control'),
      spot('midon', 'Mid-on', 59, 29, 'leg', 'inner_ring', 'Straight leg-side control'),
      spot('midwicket', 'Midwicket', 75, 43, 'leg', 'inner_ring', 'Across-line miscues'),
      spot('fineleg', 'Fine leg', 72, 82, 'leg', 'outfield', 'Protect fine deflection', true),
    ],
    notes: ['Cover is deliberately not a boundary rider: the plan must invite or pressure the drive.'],
  },
  {
    id: 'pace_inswing_attack',
    name: 'Pace — In-swing / Stumps Attack',
    intent: 'attack',
    maxOutsideCircle: 1,
    positions: [
      keeper,
      spot('slip1', '1st Slip', 43, 83, 'off', 'close', 'Outside edge from the ball that holds its line'),
      spot('legslip', 'Leg Slip', 57, 82, 'leg', 'close', 'Fine inside edge or glance', true),
      spot('gully', 'Gully', 27, 70, 'off', 'close', 'Hard-handed edge'),
      spot('point', 'Point', 18, 56, 'off', 'inner_ring', 'Save square off-side single'),
      spot('cover', 'Cover', 27, 40, 'off', 'inner_ring', 'Close the release shot'),
      spot('midoff', 'Mid-off', 41, 29, 'off', 'inner_ring', 'Straight-drive control'),
      spot('midon', 'Mid-on', 59, 29, 'leg', 'inner_ring', 'Catch the checked on-drive'),
      spot('midwicket', 'Midwicket', 75, 43, 'leg', 'inner_ring', 'Across-line catch and single prevention'),
      spot('fineleg', 'Fine leg', 72, 82, 'leg', 'outfield', 'Protect leg glance', true),
    ],
    notes: ['Do not place square leg behind the popping crease as that would create a third fielder behind square on the leg side.'],
  },
  {
    id: 'pace_fourth_stump_pressure',
    name: 'Pace — Fourth-stump Pressure',
    intent: 'pressure',
    maxOutsideCircle: 1,
    positions: [
      keeper,
      spot('slip1', '1st Slip', 43, 83, 'off', 'close', 'Outside-edge catcher'),
      spot('slip2', '2nd Slip', 36, 79, 'off', 'close', 'Thicker edge'),
      spot('gully', 'Gully', 27, 70, 'off', 'close', 'Square edge'),
      spot('bpoint', 'Backward Point', 17, 60, 'off', 'inner_ring', 'Shut off square release'),
      spot('cover', 'Cover', 26, 41, 'off', 'inner_ring', 'Save cover single'),
      spot('midoff', 'Mid-off', 41, 29, 'off', 'inner_ring', 'Save straight single'),
      spot('midon', 'Mid-on', 59, 29, 'leg', 'inner_ring', 'Straight leg-side control'),
      spot('midwicket', 'Midwicket', 75, 43, 'leg', 'inner_ring', 'Deny easy clip'),
      spot('fineleg', 'Fine leg', 72, 82, 'leg', 'outfield', 'Protect fine deflection', true),
    ],
    notes: ['Suits patient spells. If the bowler repeatedly strays straight, move a catcher only after changing the plan.'],
  },
  {
    id: 'pace_body_bouncer',
    name: 'Pace — Controlled Body / Bouncer',
    intent: 'attack',
    maxOutsideCircle: 3,
    positions: [
      keeper,
      spot('slip1', '1st Slip', 43, 83, 'off', 'close', 'Glove or fend behind'),
      spot('gully', 'Gully', 27, 70, 'off', 'close', 'Fended edge'),
      spot('point', 'Point', 18, 56, 'off', 'inner_ring', 'Save cut'),
      spot('cover', 'Cover', 27, 40, 'off', 'inner_ring', 'Off-side single control'),
      spot('midoff', 'Mid-off', 41, 29, 'off', 'inner_ring', 'Straight control'),
      spot('midon', 'Mid-on', 59, 29, 'leg', 'inner_ring', 'Straight control'),
      spot('deepbackward', 'Deep Backward Square', 88, 72, 'leg', 'boundary', 'Hook and top-edge boundary', true),
      spot('deeplongleg', 'Long Leg', 72, 91, 'leg', 'boundary', 'Fine hook and top edge', true),
      spot('deepmidwicket', 'Deep Midwicket', 90, 27, 'leg', 'boundary', 'Control the front-of-square pull'),
    ],
    notes: ['Only two leg-side fielders are behind square.', 'Use only where age, competition rules, bowler control and batter safety permit.'],
  },
  {
    id: 'pace_offside_contain',
    name: 'Pace — Off-side Containment',
    intent: 'contain',
    maxOutsideCircle: 4,
    positions: [
      keeper,
      spot('shortthird', 'Short Third', 29, 76, 'off', 'inner_ring', 'Cut off guided single'),
      spot('bpoint', 'Backward Point', 17, 60, 'off', 'inner_ring', 'Save square single'),
      spot('cover', 'Cover', 27, 42, 'off', 'inner_ring', 'Save cover single'),
      spot('midoff', 'Mid-off', 42, 30, 'off', 'inner_ring', 'Straight single control'),
      spot('deeppoint', 'Deep Point', 7, 61, 'off', 'boundary', 'Square-cut boundary'),
      spot('deepcover', 'Deep Cover', 10, 31, 'off', 'boundary', 'Cover boundary'),
      spot('longoff', 'Long-off', 33, 9, 'off', 'boundary', 'Straight off-side boundary'),
      spot('midwicket', 'Midwicket', 75, 43, 'leg', 'inner_ring', 'Close easy clip'),
      spot('fineleg', 'Fine Leg', 75, 84, 'leg', 'outfield', 'Mishit or deflection', true),
    ],
    notes: ['Bowl outside off; a straight or leg-stump miss is not protected.'],
  },
  {
    id: 'pace_legside_contain',
    name: 'Pace — Leg-side Containment',
    intent: 'contain',
    maxOutsideCircle: 4,
    positions: [
      keeper,
      spot('shortthird', 'Short Third', 29, 76, 'off', 'inner_ring', 'Outside-edge and guide'),
      spot('point', 'Point', 18, 56, 'off', 'inner_ring', 'Save cut single'),
      spot('cover', 'Cover', 27, 41, 'off', 'inner_ring', 'Close off-side release'),
      spot('midoff', 'Mid-off', 42, 30, 'off', 'inner_ring', 'Straight off-side control'),
      spot('midwicket', 'Midwicket', 75, 43, 'leg', 'inner_ring', 'Close clip single'),
      spot('deepbackward', 'Deep Backward Square', 89, 72, 'leg', 'boundary', 'Square-leg boundary', true),
      spot('fineleg', 'Fine Leg', 75, 86, 'leg', 'boundary', 'Fine boundary', true),
      spot('deepmidwicket', 'Deep Midwicket', 91, 27, 'leg', 'boundary', 'Pull and slog boundary'),
      spot('longon', 'Long-on', 67, 9, 'leg', 'boundary', 'Straight leg-side boundary'),
    ],
    notes: ['Only two leg-side fielders are behind square.', 'Requires disciplined body or stump line.'],
  },
  {
    id: 'death_wide_yorker',
    name: 'Death — Wide Yorker',
    intent: 'boundary_defence',
    maxOutsideCircle: 5,
    positions: [
      keeper,
      spot('shortthird', 'Short Third', 29, 76, 'off', 'inner_ring', 'Fine edge and guided single'),
      spot('bpoint', 'Backward Point', 17, 60, 'off', 'inner_ring', 'Square single'),
      spot('extracover', 'Extra Cover', 29, 39, 'off', 'inner_ring', 'Protect overpitched miss'),
      spot('midon', 'Mid-on', 59, 29, 'leg', 'inner_ring', 'Straight single and bowler support'),
      spot('deeppoint', 'Deep Point', 7, 61, 'off', 'boundary', 'Square boundary'),
      spot('deepcover', 'Deep Cover', 9, 30, 'off', 'boundary', 'Lofted cover boundary'),
      spot('longoff', 'Long-off', 33, 8, 'off', 'boundary', 'Straight off-side boundary'),
      spot('longon', 'Long-on', 67, 8, 'leg', 'boundary', 'Mishit straight/on side'),
      spot('deepmidwicket', 'Deep Midwicket', 91, 27, 'leg', 'boundary', 'Across-line miss and slower-ball slog'),
    ],
    notes: ['Check the competition wide interpretation before choosing the target.', 'Fine leg is intentionally up/absent; do not miss on the pads.'],
  },
  {
    id: 'death_straight_yorker',
    name: 'Death — Straight Yorker',
    intent: 'boundary_defence',
    maxOutsideCircle: 5,
    positions: [
      keeper,
      spot('shortthird', 'Short Third', 29, 76, 'off', 'inner_ring', 'Edge and ramp single'),
      spot('point', 'Point', 18, 56, 'off', 'inner_ring', 'Square single'),
      spot('cover', 'Cover', 27, 41, 'off', 'inner_ring', 'Overpitched miss on off side'),
      spot('midwicket', 'Midwicket', 75, 43, 'leg', 'inner_ring', 'Overpitched miss on leg side'),
      spot('longoff', 'Long-off', 33, 8, 'off', 'boundary', 'Straight boundary'),
      spot('longon', 'Long-on', 67, 8, 'leg', 'boundary', 'Straight boundary'),
      spot('deepcover', 'Deep Cover', 9, 30, 'off', 'boundary', 'Lofted cover miss'),
      spot('deepmidwicket', 'Deep Midwicket', 91, 27, 'leg', 'boundary', 'Slog from low full toss'),
      spot('fineleg', 'Fine Leg', 75, 86, 'leg', 'boundary', 'Inside edge and leg-stump miss', true),
    ],
    notes: ['The protected miss is low full and straight; a slot-length miss remains expensive.'],
  },
  {
    id: 'pace_slower_ball',
    name: 'Pace — Slower-ball Pitch',
    intent: 'attack',
    maxOutsideCircle: 5,
    positions: [
      keeper,
      spot('shortthird', 'Short Third', 29, 76, 'off', 'inner_ring', 'Late edge'),
      spot('point', 'Point', 18, 56, 'off', 'inner_ring', 'Square single'),
      spot('extracover', 'Extra Cover', 29, 39, 'off', 'inner_ring', 'Mishit catcher'),
      spot('midwicket', 'Midwicket', 75, 43, 'leg', 'inner_ring', 'Early-closed face mishit'),
      spot('longoff', 'Long-off', 33, 8, 'off', 'boundary', 'Lofted straight mishit'),
      spot('longon', 'Long-on', 67, 8, 'leg', 'boundary', 'Lofted straight mishit'),
      spot('deepcover', 'Deep Cover', 9, 30, 'off', 'boundary', 'Lofted off-side mishit'),
      spot('deepmidwicket', 'Deep Midwicket', 91, 27, 'leg', 'boundary', 'Slog boundary and catch'),
      spot('deepbackward', 'Deep Backward Square', 89, 72, 'leg', 'boundary', 'Early pull and top edge', true),
    ],
    notes: ['Best on a large or slow surface; use the bigger boundary for the principal mis-hit.'],
  },
  {
    id: 'spin_away_attack',
    name: 'Spin — Turning Away Attack',
    intent: 'attack',
    maxOutsideCircle: 2,
    positions: [
      keeper,
      spot('slip', 'Slip', 42, 81, 'off', 'close', 'Outside edge'),
      spot('sillypoint', 'Silly Point', 42, 65, 'off', 'close', 'Bat-pad and checked defence'),
      spot('bpoint', 'Backward Point', 18, 59, 'off', 'inner_ring', 'Square single and cut'),
      spot('cover', 'Cover', 27, 41, 'off', 'inner_ring', 'Drive pressure'),
      spot('midoff', 'Mid-off', 42, 29, 'off', 'inner_ring', 'Straight drive and charge'),
      spot('midon', 'Mid-on', 58, 29, 'leg', 'inner_ring', 'Straight leg-side control'),
      spot('midwicket', 'Midwicket', 75, 43, 'leg', 'inner_ring', 'Across-line shot'),
      spot('squareleg', 'Square Leg', 82, 59, 'leg', 'inner_ring', 'Sweep single', true),
      spot('deepmidwicket', 'Deep Midwicket', 91, 27, 'leg', 'boundary', 'Slog-sweep catch'),
    ],
    notes: ['The open temptation is an aerial hit against the turn toward the leg-side boundary catcher.'],
  },
  {
    id: 'spin_into_attack',
    name: 'Spin — Turning In Attack',
    intent: 'attack',
    maxOutsideCircle: 2,
    positions: [
      keeper,
      spot('slip', 'Slip', 42, 81, 'off', 'close', 'Edge from the straight ball'),
      spot('shortleg', 'Short Leg', 57, 66, 'leg', 'close', 'Bat-pad catch'),
      spot('bpoint', 'Backward Point', 18, 59, 'off', 'inner_ring', 'Cut single'),
      spot('cover', 'Cover', 27, 41, 'off', 'inner_ring', 'Drive single'),
      spot('midoff', 'Mid-off', 42, 29, 'off', 'inner_ring', 'Lofted straight catch/control'),
      spot('midon', 'Mid-on', 58, 29, 'leg', 'inner_ring', 'On-drive catch/control'),
      spot('midwicket', 'Midwicket', 75, 43, 'leg', 'inner_ring', 'Close the clip'),
      spot('squareleg', 'Square Leg', 82, 59, 'leg', 'inner_ring', 'Sweep and glance', true),
      spot('deepmidwicket', 'Deep Midwicket', 91, 27, 'leg', 'boundary', 'Slog-sweep catch'),
    ],
    notes: ['Keep no more than two fielders behind square on the leg side; this preset uses one.'],
  },
  {
    id: 'spin_sweep_trap',
    name: 'Spin — Sweep Trap',
    intent: 'attack',
    maxOutsideCircle: 3,
    positions: [
      keeper,
      spot('slip', 'Slip', 42, 81, 'off', 'close', 'Edge when batter abandons sweep'),
      spot('bpoint', 'Backward Point', 18, 59, 'off', 'inner_ring', 'Reverse sweep and cut single'),
      spot('cover', 'Cover', 27, 41, 'off', 'inner_ring', 'Off-side single'),
      spot('midoff', 'Mid-off', 42, 29, 'off', 'inner_ring', 'Straight control'),
      spot('midon', 'Mid-on', 58, 29, 'leg', 'inner_ring', 'Straight control'),
      spot('squareleg', 'Square Leg', 82, 59, 'leg', 'inner_ring', 'Conventional sweep single', true),
      spot('deepbackward', 'Deep Backward Square', 89, 72, 'leg', 'boundary', 'Top edge and hard sweep', true),
      spot('deepmidwicket', 'Deep Midwicket', 91, 27, 'leg', 'boundary', 'Slog sweep'),
      spot('deeppoint', 'Deep Point', 7, 61, 'off', 'boundary', 'Reverse sweep boundary'),
    ],
    notes: ['Vary fuller and top-spin length; a habitual drag-down feeds the sweep.'],
  },
  {
    id: 'spin_charge_trap',
    name: 'Spin — Batter Using Feet',
    intent: 'attack',
    maxOutsideCircle: 3,
    positions: [
      keeper,
      spot('slip', 'Slip', 42, 81, 'off', 'close', 'Edge from dip or turn'),
      spot('bpoint', 'Backward Point', 18, 59, 'off', 'inner_ring', 'Cut single'),
      spot('cover', 'Cover', 27, 41, 'off', 'inner_ring', 'Checked drive catch'),
      spot('midoff', 'Mid-off', 42, 29, 'off', 'inner_ring', 'Pressure the straight advance'),
      spot('midon', 'Mid-on', 58, 29, 'leg', 'inner_ring', 'Pressure the on-side advance'),
      spot('midwicket', 'Midwicket', 75, 43, 'leg', 'inner_ring', 'Early-closed face'),
      spot('longoff', 'Long-off', 33, 8, 'off', 'boundary', 'Lofted straight catch'),
      spot('longon', 'Long-on', 67, 8, 'leg', 'boundary', 'Lofted straight catch'),
      spot('deepmidwicket', 'Deep Midwicket', 91, 27, 'leg', 'boundary', 'Across-line charge'),
    ],
    notes: ['Keeper must be confident standing up. Change pace/trajectory rather than simply firing every ball flat.'],
  },
  {
    id: 'spin_ring_pressure',
    name: 'Spin — Ring Pressure',
    intent: 'pressure',
    maxOutsideCircle: 2,
    positions: [
      keeper,
      spot('slip', 'Slip', 42, 81, 'off', 'close', 'Edge catcher'),
      spot('bpoint', 'Backward Point', 18, 59, 'off', 'inner_ring', 'Deny square single'),
      spot('cover', 'Cover', 27, 41, 'off', 'inner_ring', 'Deny cover single'),
      spot('midoff', 'Mid-off', 42, 29, 'off', 'inner_ring', 'Deny straight single'),
      spot('midon', 'Mid-on', 58, 29, 'leg', 'inner_ring', 'Deny straight single'),
      spot('midwicket', 'Midwicket', 75, 43, 'leg', 'inner_ring', 'Deny clip single'),
      spot('squareleg', 'Square Leg', 82, 59, 'leg', 'inner_ring', 'Deny sweep single', true),
      spot('longoff', 'Long-off', 33, 8, 'off', 'boundary', 'Straight boundary'),
      spot('deepmidwicket', 'Deep Midwicket', 91, 27, 'leg', 'boundary', 'Slog boundary'),
    ],
    notes: ['Designed to create dot-ball pressure against a poor rotator, not as a universal spin field.'],
  },
];

export function fieldForBatterHand(preset: TacticalFieldPreset, hand: 'right' | 'left'): TacticalFieldPreset {
  if (hand === 'right') return preset;
  return {
    ...preset,
    positions: preset.positions.map(position => ({ ...position, x: 100 - position.x })),
  };
}

export function validateFieldPreset(preset: TacticalFieldPreset): string[] {
  const errors: string[] = [];
  if (preset.positions.length !== 10) errors.push('Field must contain wicketkeeper plus nine fielders; bowler is implicit.');
  if (preset.positions.filter(position => position.id === 'wk').length !== 1) errors.push('Field must contain exactly one wicketkeeper.');
  if (preset.positions.filter(position => position.behindSquareLeg).length > 2) errors.push('More than two fielders are behind square on the leg side.');
  const outside = preset.positions.filter(position => position.depth === 'outfield' || position.depth === 'boundary').length;
  if (outside > preset.maxOutsideCircle) errors.push(`Field declares a limit of ${preset.maxOutsideCircle} outside the circle but contains ${outside}.`);
  return errors;
}

