import type { BowlingPlan } from './types';

const allFormats: BowlingPlan['formats'] = ['multi_day', 'one_day', 't20'];

export const BOWLING_PLAN_LIBRARY: BowlingPlan[] = [
  {
    id: 'invite_drive_with_away_movement',
    title: 'Invite the drive, move it away',
    intent: 'attack',
    batterTraits: ['drives_away_from_body', 'hard_hands', 'strong_front_foot_drive', 'new_to_crease'],
    usefulCapabilities: ['outswing', 'wobble_seam', 'accurate_fourth_stump'],
    phases: ['new_ball', 'powerplay', 'wicket_push'],
    formats: allFormats,
    line: 'Start on off stump and finish around fourth stump; make the batter play often enough to create doubt.',
    length: 'Full enough to draw a front-foot stroke, but not half-volley length.',
    sequence: ['Establish two balls on a playable fourth-stump line.', 'Repeat from the same release with away movement.', 'Use the straighter ball only after the front-foot response is committed.'],
    dismissalRoutes: ['Caught wicketkeeper/slip', 'Gully from a hard-handed square edge', 'Bowled or lbw with the straighter variation'],
    scoringAreasConceded: ['A controlled straight or cover drive is the calculated invitation.'],
    fieldPresetId: 'pace_outswing_attack',
    rationale: 'A strong drive can also be a dismissal opportunity when the length is just short of a half-volley and catchers match the expected edge.',
    executionRisk: 'Overpitching turns the invitation into the batter’s strength; bowling too wide lets the batter leave.',
    changeTriggers: ['Batter repeatedly leaves without risk', 'No lateral movement after 6–12 balls', 'Bowler cannot control the fuller length'],
  },
  {
    id: 'fourth_stump_dot_pressure',
    title: 'Fourth-stump patience',
    intent: 'pressure',
    batterTraits: ['strong_leg_side', 'poor_strike_rotation', 'plays_early', 'new_to_crease'],
    usefulCapabilities: ['accurate_fourth_stump', 'wobble_seam', 'outswing'],
    phases: ['new_ball', 'middle_overs', 'old_ball', 'run_defence'],
    formats: allFormats,
    line: 'Relentless fourth-stump channel; avoid feeding the pads.',
    length: 'Top of off stump/good length, adjusted for bounce.',
    sequence: ['Build three or four dots in the same channel.', 'Use a slightly fuller ball when the batter begins reaching.', 'Use the straighter seam only as a surprise.'],
    dismissalRoutes: ['Outside edge', 'Inside edge onto stumps', 'Frustration drive or across-line shot'],
    scoringAreasConceded: ['A difficult straight-bat single is preferable to a leg-side release.'],
    fieldPresetId: 'pace_fourth_stump_pressure',
    rationale: 'Denying the preferred leg-side scoring area can make a batter manufacture across the line or reach away from the body.',
    executionRisk: 'A straight miss gives an easy clip; a short-wide miss feeds the cut.',
    changeTriggers: ['Batter comfortably rotates through cover/point', 'Bowler drifts onto pads twice in an over', 'Required run rate makes dots less valuable than boundary protection'],
  },
  {
    id: 'front_pad_inswing',
    title: 'Attack the front pad and stumps',
    intent: 'attack',
    batterTraits: ['falls_across_front_pad', 'commits_front_foot_early', 'stays_leg_side_of_ball'],
    usefulCapabilities: ['inswing', 'skiddy', 'reverse_swing'],
    phases: ['new_ball', 'old_ball', 'wicket_push'],
    formats: allFormats,
    line: 'Off stump to middle-and-off, moving into the pad/stumps; keep it legal and avoid starting down leg.',
    length: 'Full, threatening the base of the stumps and front pad.',
    sequence: ['Show a ball that holds its line outside off.', 'Repeat from the same action with movement in.', 'Follow with the straighter ball if the batter begins guarding the inside edge.'],
    dismissalRoutes: ['LBW', 'Bowled', 'Inside edge to keeper/leg slip', 'Checked on-drive to mid-on'],
    scoringAreasConceded: ['A well-executed straight drive is accepted.'],
    fieldPresetId: 'pace_inswing_attack',
    rationale: 'A batter who falls across or plants early has less capacity to adjust to late movement toward the stumps.',
    executionRisk: 'Starting too straight produces leg-side runs and reduces lbw probability.',
    changeTriggers: ['Swing is occurring too early and is easily negotiated', 'Batter remains balanced and scores through midwicket', 'Bowler loses the stumps-side line'],
  },
  {
    id: 'controlled_short_ball',
    title: 'Controlled short-ball test',
    intent: 'attack',
    batterTraits: ['weak_against_short_ball', 'commits_front_foot_early', 'tailender'],
    usefulCapabilities: ['high_pace', 'steep_bounce', 'bouncer_control'],
    phases: ['wicket_push', 'middle_overs', 'old_ball'],
    formats: allFormats,
    line: 'At the body or shoulder line, not indiscriminately at the head.',
    length: 'Short enough to climb toward the upper body without becoming predictable.',
    sequence: ['Set the batter back with one controlled short ball.', 'Follow with top-of-off length.', 'Use the full straight ball once weight stays back.'],
    dismissalRoutes: ['Glove/fend to keeper or cordon', 'Top edge to fine-leg boundary riders', 'Bowled/lbw from the follow-up full ball'],
    scoringAreasConceded: ['Single into the leg side is acceptable if the boundary is protected.'],
    fieldPresetId: 'pace_body_bouncer',
    rationale: 'The short ball is most effective as part of a length contrast, not as a repeated default.',
    executionRisk: 'Poor direction or insufficient pace feeds a pull; repeated short bowling can be dangerous or illegal.',
    changeTriggers: ['Batter controls the pull/hook', 'Bowler cannot control height or direction', 'Umpire warning or local limit reached'],
    safetyNote: 'Never recommend automatically for juniors. Confirm local age rules, protective equipment, competition limits and bowler control; the umpire remains the judge of danger and fairness.',
  },
  {
    id: 'cut_off_the_cut',
    title: 'Cramp the strong cut',
    intent: 'pressure',
    batterTraits: ['strong_cut', 'boundary_hitter_square_off'],
    usefulCapabilities: ['accurate_fourth_stump', 'inswing', 'skiddy'],
    phases: ['powerplay', 'middle_overs', 'run_defence'],
    formats: allFormats,
    line: 'Tighter to off stump or into the hip; remove width while retaining an off-side catching option.',
    length: 'Back of a good length or fuller—avoid short-and-wide.',
    sequence: ['Deny width for three balls.', 'Use a fuller attacking ball at off stump.', 'Only use the surprise short ball with body-line control.'],
    dismissalRoutes: ['Bowled/lbw', 'Cramped cut edge', 'Across-line leg-side miscue'],
    scoringAreasConceded: ['Controlled straight single rather than square boundary.'],
    fieldPresetId: 'pace_fourth_stump_pressure',
    rationale: 'A cut needs width and usually room to free the hands; changing line without abandoning top-of-off pressure removes the preferred shot.',
    executionRisk: 'A drag-down or wide miss lands directly in the strength.',
    changeTriggers: ['Batter creates room successfully', 'Pitch bounce makes back-of-length sit up', 'Leg-side singles become effortless'],
  },
  {
    id: 'offside_fence',
    title: 'Off-side fence with wide hard length',
    intent: 'contain',
    batterTraits: ['strong_leg_side', 'boundary_hitter_square_leg', 'targets_short_boundary'],
    usefulCapabilities: ['accurate_fourth_stump', 'wide_yorker', 'off_cutter'],
    phases: ['middle_overs', 'run_defence', 'death'],
    formats: ['one_day', 't20'],
    line: 'Outside off stump, away from the batter’s strongest leg-side arc.',
    length: 'Hard length in middle overs; wide yorker at the death.',
    sequence: ['Establish the wide channel.', 'Change pace without changing the visual line.', 'Use a straight yorker only if the batter premeditates movement across.'],
    dismissalRoutes: ['Slice to deep point/cover', 'Edge to keeper/short third', 'Mishit from reaching across the line'],
    scoringAreasConceded: ['One to cover or point when boundary prevention is the priority.'],
    fieldPresetId: 'pace_offside_contain',
    rationale: 'The field and line jointly move the contest away from the batter’s strongest boundary zone.',
    executionRisk: 'A wide call or slot ball outside off can be expensive; local wide interpretations vary.',
    changeTriggers: ['Batter repeatedly reaches and hits over cover', 'Batter moves across early', 'Short off-side boundary makes the plan unfavourable'],
  },
  {
    id: 'body_line_legside_fence',
    title: 'Body line into a protected leg side',
    intent: 'contain',
    batterTraits: ['stays_leg_side_of_ball', 'boundary_hitter_square_off', 'strong_cut'],
    usefulCapabilities: ['skiddy', 'bouncer_control', 'off_cutter'],
    phases: ['middle_overs', 'run_defence', 'death'],
    formats: ['one_day', 't20'],
    line: 'Hip to middle-and-leg, following room only within the competition’s wide and safety rules.',
    length: 'Hard length into the body; yorker when the batter backs away early.',
    sequence: ['Cramp the first attempt to create room.', 'Repeat with pace off into the surface.', 'Use the straight yorker when the batter’s base opens.'],
    dismissalRoutes: ['Cramped pull to leg-side boundary rider', 'Bowled while backing away', 'Mishit to midwicket'],
    scoringAreasConceded: ['Leg-side single is preferable to free arms through cover.'],
    fieldPresetId: 'pace_legside_contain',
    rationale: 'Following a batter who seeks off-side room removes leverage, provided the bowler has control and the field protects the likely pull/clip.',
    executionRisk: 'Drifting too far down leg concedes wides; sitting up at medium pace feeds a pull.',
    changeTriggers: ['Batter ramps or glances safely', 'Bowler cannot follow movement legally', 'Only a short leg-side boundary is available'],
  },
  {
    id: 'slower_ball_to_early_swing',
    title: 'Pace-off against an early swing',
    intent: 'attack',
    batterTraits: ['plays_early', 'commits_front_foot_early', 'vulnerable_to_change_of_pace'],
    usefulCapabilities: ['slower_ball', 'off_cutter', 'leg_cutter', 'change_of_pace'],
    phases: ['middle_overs', 'death', 'run_defence'],
    formats: ['one_day', 't20'],
    line: 'At the stumps or just outside off, keeping the slower ball hittable enough to induce commitment.',
    length: 'Into the pitch or just short of the slot, chosen for the surface.',
    sequence: ['Show normal pace from the same action.', 'Use pace off to the larger protected side.', 'Return to yorker/full pace when the batter waits deeper.'],
    dismissalRoutes: ['Early lofted miscue', 'Leading edge', 'Bowled by cutter or follow-up pace'],
    scoringAreasConceded: ['A single to the long boundary is acceptable.'],
    fieldPresetId: 'pace_slower_ball',
    rationale: 'A batter who commits early loses shape when pace, dip or grip changes without an obvious action cue.',
    executionRisk: 'An obvious or overpitched slower ball becomes a slot ball.',
    changeTriggers: ['Batter waits and hits late', 'Wet ball prevents reliable grip', 'Pitch is too true for cutters'],
  },
  {
    id: 'wide_yorker_death',
    title: 'Wide-yorker boundary defence',
    intent: 'boundary_defence',
    batterTraits: ['boundary_hitter_straight', 'strong_leg_side', 'commits_front_foot_early'],
    usefulCapabilities: ['wide_yorker', 'changes_crease_angle'],
    phases: ['death', 'run_defence'],
    formats: ['one_day', 't20'],
    line: 'Inside the wide guideline target appropriate to the competition, outside the batter’s hitting arc.',
    length: 'Blockhole; acceptable miss is low and wide, not slot length.',
    sequence: ['Set the crease angle and wide target.', 'Repeat if execution is strong.', 'Use a straight yorker or body ball only when the batter moves across early.'],
    dismissalRoutes: ['Edge to keeper/short third', 'Slice to deep point/cover', 'Stumped/run out after overbalancing'],
    scoringAreasConceded: ['A hard-run single to the off side.'],
    fieldPresetId: 'death_wide_yorker',
    rationale: 'The line lengthens the swing path and protects the most likely sliced or lofted miss.',
    executionRisk: 'Small error margins: too wide is an extra; too full can become a full toss; too short becomes slot length.',
    changeTriggers: ['Two wides or failed yorkers', 'Batter moves across before release', 'Off-side boundary is unusually short'],
  },
  {
    id: 'straight_yorker_death',
    title: 'Straight yorker with protected miss',
    intent: 'boundary_defence',
    batterTraits: ['vulnerable_to_yorker', 'deep_in_crease', 'stays_leg_side_of_ball'],
    usefulCapabilities: ['straight_yorker', 'reverse_swing', 'skiddy'],
    phases: ['death', 'wicket_push', 'run_defence'],
    formats: allFormats,
    line: 'Base of middle/off, adjusted if the batter moves.',
    length: 'Yorker; low full toss is the safer miss, never slot length.',
    sequence: ['Show hard length or slower ball.', 'Attack the base of the stumps.', 'Repeat only while the release remains controlled.'],
    dismissalRoutes: ['Bowled', 'LBW', 'Inside edge', 'Low catch to straight boundary rider'],
    scoringAreasConceded: ['One from a dug-out yorker.'],
    fieldPresetId: 'death_straight_yorker',
    rationale: 'A deep crease reduces reaction space and can make a base-of-stumps target especially difficult.',
    executionRisk: 'A length miss becomes the easiest ball to loft.',
    changeTriggers: ['Release point deteriorates', 'Batter ramps from a stable base', 'Wet ball makes the yorker unsafe to execute'],
  },
  {
    id: 'spin_away_from_edge',
    title: 'Turn away from the outside edge',
    intent: 'attack',
    batterTraits: ['weak_to_ball_turning_away', 'hard_hands', 'crease_bound_to_spin', 'new_to_crease'],
    usefulCapabilities: ['turns_away_from_batter', 'flight_and_dip', 'stock_spin_control'],
    phases: ['middle_overs', 'wicket_push', 'old_ball'],
    formats: allFormats,
    line: 'Threaten off stump, allowing turn to take the ball toward the outside edge rather than starting too wide.',
    length: 'Full enough to draw the batter forward, with dip keeping it below driving length.',
    sequence: ['Establish stock turn from an off-stump line.', 'Add flight or a wider crease angle.', 'Use the straighter ball once the batter plays for turn.'],
    dismissalRoutes: ['Caught slip/keeper', 'Stumped', 'Bowled/lbw by straighter ball', 'Mishit against turn'],
    scoringAreasConceded: ['A difficult drive with the turn is the invitation.'],
    fieldPresetId: 'spin_away_attack',
    rationale: 'Starting at the stumps makes both the turning ball and the straight variation relevant.',
    executionRisk: 'Starting too wide removes bowled/lbw and allows the batter to leave or cut.',
    changeTriggers: ['No turn or dip', 'Batter uses feet and reaches pitch safely', 'Sweep becomes controlled'],
  },
  {
    id: 'spin_into_pad',
    title: 'Turn into pad and bat-pad',
    intent: 'attack',
    batterTraits: ['weak_to_ball_turning_in', 'falls_across_front_pad', 'hard_hands', 'crease_bound_to_spin'],
    usefulCapabilities: ['turns_into_batter', 'arm_ball_or_slider', 'flight_and_dip'],
    phases: ['middle_overs', 'wicket_push', 'old_ball'],
    formats: allFormats,
    line: 'Outside off to off stump, turning toward pad and stumps.',
    length: 'Driving length with dip; avoid easy half-volleys on the pads.',
    sequence: ['Turn two balls into the front pad.', 'Use one that drifts or starts wider.', 'Deliver the arm ball/slider when the batter plays for turn.'],
    dismissalRoutes: ['Bat-pad to short leg', 'LBW/bowled', 'Inside edge', 'Checked on-drive'],
    scoringAreasConceded: ['Controlled single toward cover is preferable to an easy clip.'],
    fieldPresetId: 'spin_into_attack',
    rationale: 'Turn into a planted front side creates bat-pad and inside-edge chances while the straight ball threatens the outside edge/stumps.',
    executionRisk: 'Too straight or short feeds the leg side.',
    changeTriggers: ['Batter sweeps safely', 'Batter consistently reaches the pitch', 'Bowler cannot start outside off'],
  },
  {
    id: 'topspin_to_sweeper',
    title: 'Change bounce against the sweep',
    intent: 'attack',
    batterTraits: ['strong_sweep', 'weak_sweep', 'strong_reverse_sweep'],
    usefulCapabilities: ['top_spinner', 'flight_and_dip', 'change_of_pace'],
    phases: ['middle_overs', 'wicket_push'],
    formats: allFormats,
    line: 'At off/middle, adjusted so the batter must sweep from a less comfortable line.',
    length: 'Alternate a fuller dipping ball with one fractionally shorter that bounces more.',
    sequence: ['Show stock spin at sweep length.', 'Use top-spin or extra bounce.', 'Follow with the quicker straighter ball if the head falls across.'],
    dismissalRoutes: ['Top edge to backward square', 'LBW/bowled under the sweep', 'Reverse-sweep catch at point'],
    scoringAreasConceded: ['Single to the protected sweep side.'],
    fieldPresetId: 'spin_sweep_trap',
    rationale: 'The field does not merely defend the sweep; length and bounce variation change the contact point and create catching chances.',
    executionRisk: 'Repeated short balls make the sweep/pull easier and abandon the stumps.',
    changeTriggers: ['Batter controls both sweep directions', 'Bounce is too low for top-spin', 'Boundary riders are poorly placed for ground dimensions'],
  },
  {
    id: 'spin_to_batter_using_feet',
    title: 'Disrupt a batter using their feet',
    intent: 'attack',
    batterTraits: ['uses_feet_to_spin', 'boundary_hitter_straight'],
    usefulCapabilities: ['flight_and_dip', 'change_of_pace', 'changes_crease_angle', 'arm_ball_or_slider'],
    phases: ['middle_overs', 'wicket_push'],
    formats: allFormats,
    line: 'Keep the stumps in play; vary angle without gifting leg-side line.',
    length: 'Mix dipping full length with a quicker, slightly shorter response to early movement.',
    sequence: ['Invite the advance with flight and protection straight.', 'Pull the length back or increase dip when movement starts.', 'Use the quicker straight ball once the batter premeditates.'],
    dismissalRoutes: ['Stumped', 'Lofted catch long-on/off', 'Bowled by quicker ball', 'Mishit to midwicket'],
    scoringAreasConceded: ['Single down the ground if the batter stays controlled.'],
    fieldPresetId: 'spin_charge_trap',
    rationale: 'A changing trajectory and pace make the batter commit before the final length is clear.',
    executionRisk: 'Flat darts alone become predictable; overflighted slot balls feed the straight hit.',
    changeTriggers: ['Keeper cannot stand up safely', 'Batter repeatedly reaches the pitch', 'Straight boundaries are too short for the selected protection'],
  },
  {
    id: 'spin_dot_ball_squeeze',
    title: 'Ring-field squeeze',
    intent: 'pressure',
    batterTraits: ['poor_strike_rotation', 'boundary_hitter_straight', 'new_to_crease'],
    usefulCapabilities: ['stock_spin_control', 'change_of_pace', 'flight_and_dip'],
    phases: ['middle_overs', 'run_defence'],
    formats: ['one_day', 't20'],
    line: 'At the stumps with the stock turn taking the ball toward the less productive side.',
    length: 'Good spin length that prevents both easy drive and back-foot single.',
    sequence: ['Build three dots with stock control.', 'Use flight when the batter forces the pace.', 'Use the straight/quick ball when they create room.'],
    dismissalRoutes: ['Lofted straight catch', 'Slog to deep midwicket', 'Bowled/lbw while manufacturing a single'],
    scoringAreasConceded: ['Single to the least dangerous boundary side after pressure is established.'],
    fieldPresetId: 'spin_ring_pressure',
    rationale: 'Against a weak rotator, six protected singles can be less valuable than a tight ring that turns the next boundary attempt into a higher-risk shot.',
    executionRisk: 'If the batter rotates comfortably, the attacking value disappears.',
    changeTriggers: ['Two easy singles in an over', 'Non-striker is a more favourable matchup', 'Required rate permits low-risk rotation'],
  },
  {
    id: 'tailender_stumps_first',
    title: 'Tailender: stumps first, surprise short',
    intent: 'attack',
    batterTraits: ['tailender', 'deep_in_crease', 'falls_across_front_pad'],
    usefulCapabilities: ['straight_yorker', 'inswing', 'skiddy', 'bouncer_control'],
    phases: ['wicket_push', 'old_ball', 'death'],
    formats: allFormats,
    line: 'Middle/off stump as the default.',
    length: 'Full at the stumps, with an occasional controlled short ball only as contrast.',
    sequence: ['Attack the stumps twice.', 'Use a controlled short ball only if safe and legal.', 'Return immediately to the base of the stumps.'],
    dismissalRoutes: ['Bowled', 'LBW', 'Glove/top edge', 'Simple catch from a straight-bat miscue'],
    scoringAreasConceded: ['Single that exposes the stronger batter may be tactically undesirable; context decides.'],
    fieldPresetId: 'pace_inswing_attack',
    rationale: 'Lower-order batters often have less reliable defensive alignment; removing the need for an edge keeps the primary dismissal routes simple.',
    executionRisk: 'Searching for a spectacular short-ball dismissal can waste balls and create runs.',
    changeTriggers: ['Tailender demonstrates sound straight defence', 'Need to prevent a single late in the over', 'Short-ball safety or legal limit applies'],
    safetyNote: 'Short bowling remains optional and must pass all age, law and control checks.',
  },
];

