/**
 * Diagnostic Rejection Codes Taxonomy
 */
export const REJECTION_CODES = {
  COHORT_NOT_ELIGIBLE: 'COHORT_NOT_ELIGIBLE',
  COACH_LEVEL_TOO_LOW: 'COACH_LEVEL_TOO_LOW',
  TOO_FEW_PARTICIPANTS: 'TOO_FEW_PARTICIPANTS',
  TOO_MANY_PARTICIPANTS: 'TOO_MANY_PARTICIPANTS',
  VENUE_NOT_SUPPORTED: 'VENUE_NOT_SUPPORTED',
  NETS_REQUIRED: 'NETS_REQUIRED',
  OPEN_SPACE_REQUIRED: 'OPEN_SPACE_REQUIRED',
  EQUIPMENT_MISSING: 'EQUIPMENT_MISSING',
  SAFETY_RULE_BLOCK: 'SAFETY_RULE_BLOCK',
  SESSION_SLOT_NOT_ALLOWED: 'SESSION_SLOT_NOT_ALLOWED',
  FOCUS_NOT_COVERED: 'FOCUS_NOT_COVERED',
  DURATION_TOO_SHORT: 'DURATION_TOO_SHORT',
  DURATION_TOO_LONG: 'DURATION_TOO_LONG',
  NO_ACTIVITY_FOR_REQUIRED_BLOCK: 'NO_ACTIVITY_FOR_REQUIRED_BLOCK',
  NO_VALID_REPLACEMENT: 'NO_VALID_REPLACEMENT',
  TEMPLATE_CANNOT_FIT_DURATION: 'TEMPLATE_CANNOT_FIT_DURATION',
  LOCAL_RULESET_RESTRICTION: 'LOCAL_RULESET_RESTRICTION',
  UNKNOWN_OR_UNRESOLVED_RULE: 'UNKNOWN_OR_UNRESOLVED_RULE'
};
